server.port=8094
server.servlet.context-path=/DSA-NoSQL-Neo4JService/rest

neo4j.data.source.DB_URL=bolt://127.0.0.1:7687
neo4j.data.source.USER=neo4j
neo4j.data.source.PASS=Neo12345j

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis