server.port=8092
server.servlet.context-path=/DSA_SQL_JPAService_PostgreSQL/rest

spring.datasource.url=jdbc:postgresql://localhost:5433/PTS_DS2?currentSchema=operationshr
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=info

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis